app/api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework_nested import routers

from api import views

router = routers.SimpleRouter()
router.register(r'users', views.UserViewSet)
router.register(r'punches', views.ChallengeViewSet, base_name='challenge')

users_router = routers.NestedSimpleRouter(router, r'users', lookup='user')
users_router.register(r'followers', views.FollowerViewSet, base_name='follower')
users_router.register(r'follows', views.FollowsViewSet, base_name='follows')


urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^', include(users_router.urls)),
)

app/yolo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . import views


urlpatterns = patterns('',
    #url(r'^users', include(user_urls)),
    #url(r'^punches', include(challenge_urls)),
    #url(r'^photos', include(photo_urls)),
    #Basic YoloPunch functionality
    url(r'^$', views.home, name='home'),
    url(r'^demo/$', views.demo, name='demo'),
    url(r'^search/$', views.search, name='search'),
    url(r'^top/$', views.top_all, name='top_all' ),
    url(r'^top/users/$', views.top_users, name='top_users'),
    url(r'^top/punches/$', views.top_challenges, name='top_challenges'),
    url(r'^(?P<username>[a-z0-9.-_]+)/following/$', views.following, name='user_following'),
    url(r'^(?P<username>[a-z0-9.-_]+)/followers/$', views.followers, name='user_followers'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/$',
         views.challanges_all, name='user_challenges_all'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/created/$',
         views.challanges_created, name='user_challenges_created'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/completed/$',
         views.challanges_completed, name='user_challenges_completed'),
    url(r'^(?P<username>[a-z0-9.-_]+)/$', views.user, name='user'),
    url(r'^styleguide$', views.styleguide, name='styleguide'),


    # Examples:
    # url(r'^$', 'yolopunch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url( r'^$', views.index, name='index'),

    #url(r'^admin/', include(admin.site.urls)),
)

app/yolopunch/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from api.views import LoginView

from rest_framework.urlpatterns import format_suffix_patterns

#our login should be able to render html or json, as requested
urlpatterns = patterns('',
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'api'])

urlpatterns += patterns('',
    url(r'^api/v1/', include('api.urls', namespace='api')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url('^', include('yolo.urls', namespace='yolo')),
)

app/yolo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    points = models.IntegerField(default=5) #let's give 5 points for registration!
    follows = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    twitter = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


 # This function will create a UserProfile whenever a User is created
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Challenge(models.Model):
    title = models.CharField(max_length=100)#
    description = models.CharField(max_length=500)
    author = models.ForeignKey(User, related_name='challenges')
    recipients = models.ManyToManyField(User)
    pub_date = models.DateTimeField(auto_now_add=True)
    exp_date = models.DateTimeField()

class Photo(models.Model):
    challenge = models.ForeignKey(Challenge, related_name='photos')
    image = models.ImageField(upload_to="%Y/%m/%d")

app/yolo/forms.py
from django import forms
from django.contrib.auth.models import User

class ChallengeForm(forms.Form):
    name = forms.CharField(label='Punch name', min_length=3, max_length=100)
    recipient = forms.CharField(label='Recipient')
    desc = forms.CharField(label='Description', min_length=3, max_length=500,
                                            widget=forms.Textarea)


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name')

app/yolo/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.forms import ValidationError
from django.utils.translation import ugettext as _
from .models import Challenge

from . import forms


def home(request):
    if request.user.is_authenticated():
        challenge_form = forms.ChallengeForm()
        return render(request, 'yolo/feed.html', {'user': request.user, 'challenge_form' : challenge_form})
    else:
        return render(request, 'yolo/index.html')

def demo(request):
    form = forms.RegisterForm()
    return render(request, 'yolo/demo.html', {'form': form})

def top_users(request):
    return render(request, 'yolo/top.html', {'action_name': 'users'})

def following(request, username):
    user = get_object_or_404(User, username=username)
    #get following list and pass in to the template
    return render(request, 'yolo/following_followers.html', {'user': user, 'action_name': 'following'})

def followers(request, username):
    user = get_object_or_404(User, username=username)
    #get followers list and pass in to the template
    return render(request, 'yolo/following_followers.html', {'user': user, 'action_name': 'followers'})


def search(request):
    return render(request, 'yolo/search.html')

def top_all(request):
    return render(request, 'yolo/top.html', {'action_name': 'all'})

def top_users(request):
    return render(request, 'yolo/top.html', {'action_name': 'users'})

def top_challenges(request):
    return render(request, 'yolo/top.html', {'action_name': 'punches'})

def user(request, username):
    user = get_object_or_404(User, username=username)
    return render(request, 'yolo/user.html', {'user': user})

def challanges_all(request, username):
    #show both created and completed challanges
    #challanges =
    user = get_object_or_404(User, username=username)
    return render(request, 'yolo/challenges.html', {'user': user, 'action_name':'all'})

def challanges_created(request, username):
    #show created challanges
    #challanges =
    user = get_object_or_404(User, username=username)
    return render(request, 'yolo/challenges.html', {'user': user, 'action_name':'created'})

def challanges_completed(request, username):
    #show created challanges
    #challanges =
    user = get_object_or_404(User, username=username)
    return render(request, 'yolo/challenges.html', {'user': user, 'action_name':'completed'})


def styleguide(request):
    return render(request, 'yolo/styleguide.html')

app/templates/yolo/challange_form.html
<form action="{% url 'yolo:challanges' 'soin08' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>attach...</button>
    <button type="submit">publish</button>
</form>

app/templates/yolo/challenge_form.html
<form action="{% url 'yolo:user_challenges_all' user.get_username%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>attach...</button>
    <button type="submit">publish</button>
</form>

app/templates/yolo/challenges.html
{% extends "base.html" %}

{% block title %}
    {{ user.get_full_name }}'s punches: {{ action_name }}
{% endblock title %}

{% block content %}
    <h1>{{user.get_full_name}}</h1>
    <h1>Punches: {{ action_name }}</h1>
     <a href="{% url 'yolo:user_challenges_all' user.get_username %}">
        <button>all</button>
     </a>
     <a href="{% url 'yolo:user_challenges_created' user.get_username %}">
        <button>created</button>
     </a>
<a href="{% url 'yolo:user_challenges_completed' user.get_username %}">
        <button>completed</button>
     </a>
{% endblock content %}

app/templates/yolo/demo.html
{% extends "base.html" %}

{% block content %}

    <form action="/api/v1/users/" method="POST">
    {{ form.as_p }}
    <button type="submit">Submit!</button>
    </form>

{% endblock content %}

app/templates/yolo/feed.html
{% extends "base.html" %}

{% block title %}YoloPunch{% endblock title %}

{% block content %}
    <h2>{{ user.get_full_name }} (<a href="{% url 'auth_logout' %}">Logout</a>)</h2>
    {% include "yolo/challenge_form.html" with form=challenge_form user=user only %}
{% endblock content %}

app/templates/yolo/following_followers.html
{% extends "base.html" %}

{% block title %}
    {{ action_name }}
{% endblock title %}

{% block content %}
    <h1> {{ user.get_full_name }}'s {{ action_name }} page</h1>
{% endblock content %}

app/templates/yolo/index.html
{% extends "base.html" %}
{% block title %}YoloPunch{% endblock title %}

{% block content %}
    <h1>Welcome to YoloPunch!</h1>
    <h2>Welcome to YoloPunch!</h2>
    <h3>Welcome to YoloPunch!</h3>
    <p>YoloPunch is a social platform for challenges of any kind</p>
    <div class="row">
      <div class="col s12 m4">
        <div class="center promo promo-example">
          <i class="mdi-image-flash-on large"></i>
          <p class="promo-caption">Speeds up development</p>
          <p class="light center">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.</p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="center promo promo-example">
          <i class="mdi-social-group large"></i>
          <p class="promo-caption">User Experience Focused</p>
          <p class="light center">By utilizing elements and principles of Material Design, we were able to create a framework that focuses on User Experience.</p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="center promo promo-example">
          <i class="mdi-action-settings large"></i>
          <p class="promo-caption">Easy to work with</p>
          <p class="light center">We have provided detailed documentation as well as specific code examples to help new users get started.</p>
        </div>
      </div>
    </div>

    <h1>Ready to send and accept challenges?</h1>
    <h2><a href="{% url 'auth_login' %}">Login!</a></h2>


{% endblock content %}

app/templates/yolo/punch_form.html
<form action="{% url 'punches' 'soin08' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>attach...</button>
    <button type="submit">publish</button>
</form>

app/templates/yolo/search.html
{% extends "base.html" %}

{% block title %}
    Search
{% endblock title %}

{% block content %}
    <h1>Search page</h1>
{% endblock content %}

app/templates/yolo/top.html
{% extends "base.html" %}

{% block title %}
    Top
{% endblock title %}

{% block content %}
    <h1>Top page: {{action_name}}</h1>
    <a href="{% url 'yolo:top_all' %}"><button>all</button></a>
    <a href="{% url 'yolo:top_users' %}"><button>users</button></a>
    <a href="{% url 'yolo:top_challenges' %}"><button>punches</button></a>
{% endblock content %}

app/templates/yolo/user.html
{% extends "base.html" %}

{% block title %}
    {{ user.get_full_name}}
{% endblock title %}

{% block content %}
    <h1>{{ user.get_full_name}}'s profile</h1>
    <a href="{% url 'yolo:user_following' user.get_username %}"><button>following</button></a>
    <a href="{% url 'yolo:user_followers' user.get_username %}"><button>followers</button></a>
    <a href="{% url 'yolo:user_challenges_all' user.get_username %}"><button>punches</button></a>
{% endblock content %}