app/api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework_nested import routers

from api import views

router = routers.SimpleRouter()
router.register(r'users', views.UserViewSet)
router.register(r'punches', views.ChallengeViewSet, base_name='challenge')

users_router = routers.NestedSimpleRouter(router, r'users', lookup='user')
users_router.register(r'followers', views.FollowerViewSet, base_name='follower')
users_router.register(r'follows', views.FollowsViewSet, base_name='follows')


urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^', include(users_router.urls)),
)

app/yolo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . import views


urlpatterns = patterns('',
    #url(r'^users', include(user_urls)),
    #url(r'^punches', include(challenge_urls)),
    #url(r'^photos', include(photo_urls)),
    #Basic YoloPunch functionality
    url(r'^$', views.home, name='home'),
    url(r'^demo/$', views.demo, name='demo'),
    url(r'^search/$', views.search, name='search'),
    url(r'^top/$', views.top_all, name='top_all' ),
    url(r'^top/users/$', views.top_users, name='top_users'),
    url(r'^top/punches/$', views.top_challenges, name='top_challenges'),
    url(r'^(?P<username>[a-z0-9.-_]+)/following/$', views.following, name='user_following'),
    url(r'^(?P<username>[a-z0-9.-_]+)/followers/$', views.followers, name='user_followers'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/$',
         views.challanges_all, name='user_challenges_all'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/created/$',
         views.challanges_created, name='user_challenges_created'),
    url(r'^(?P<username>[a-z0-9.-_]+)/punches/completed/$',
         views.challanges_completed, name='user_challenges_completed'),
    url(r'^(?P<username>[a-z0-9.-_]+)/$', views.user, name='user'),
    url(r'^styleguide$', views.styleguide, name='styleguide'),


    # Examples:
    # url(r'^$', 'yolopunch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url( r'^$', views.index, name='index'),

    #url(r'^admin/', include(admin.site.urls)),
)

app/yolopunch/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from api.views import LoginView

from rest_framework.urlpatterns import format_suffix_patterns

#our login should be able to render html or json, as requested
urlpatterns = patterns('',
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'api'])

urlpatterns += patterns('',
    url(r'^api/v1/', include('api.urls', namespace='api')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url('^', include('yolo.urls', namespace='yolo')),
)

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{% static "images/touch/chrome-touch-icon-192x192.png" %}">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="YoloPunch">
    <link rel="apple-touch-icon" href="{% static "images/touch/apple-touch-icon.png" %}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content=""{% static "images/touch/ms-touch-icon-144x144-precomposed.png" %}>
    <meta name="msapplication-TileColor" content="#3372DF">

    <!-- Styles -->
    <!--For production we only include lib.min.css generated by Gulp -->
    <!--Currently there is no lib.min.css since there is no main css in bower  -->
    <!-- //build:css-lib -->
    <!--For development we include (automatically) all main bower css files -->
    <!-- //bower:css -->
    <!-- //endinject -->
    <!-- //endbuild -->

    <!--For production we only include app.min.css generated by Gulp -->
    <!-- build:css-app -->
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
    <!-- endbuild -->

  </head>
  <body ng-app="{% block ng-app %}{% endblock %}" ng-strict-di>
    <!-- Header -->
    <header>
      <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">yolopunch</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="mdi-navigation-menu"></i>
          </a>
          <ul class="right hide-on-med-and-down">
            <li><a href="/">home</a></li>
            <li><a href="{% url 'yolo:top_all' %}">top</a></li>
            <li><a href="{% url 'yolo:user' 'demouser' %}">demouser</a></li>
            <li><a href="{% url 'auth_login' %}">login</a></li>
            <li><a href="{% url 'registration_register' %}">register</a></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="/">home</a></li>
            <li><a href="{% url 'yolo:top_all' %}">top</a></li>
            <li><a href="{% url 'yolo:user' 'demouser' %}">demouser</a></li>
            <li><a href="{% url 'auth_login' %}">login</a></li>
            <li><a href="{% url 'registration_register' %}">register</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Main -->
    <main>
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>
    <!-- Footer -->
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>

    <!--For production we only include lib.min.js generated by Gulp -->
    <!-- build:js-lib -->
    <!--For development we include (automatically) all main js bower files -->
    <!-- bower:js -->
    <script src="{% static "bower_components/jquery/dist/jquery.js" %}"></script>
    <script src="{% static "bower_components/angular/angular.js" %}"></script>
    <script src="{% static "bower_components/angular-cookies/angular-cookies.js" %}"></script>
    <script src="{% static "bower_components/angular-materialize/src/angular-materialize.js" %}"></script>
    <script src="{% static "bower_components/angular-animate/angular-animate.js" %}"></script>
    <script src="{% static "bower_components/materialize/bin/materialize.js" %}"></script>
    <!-- endinject -->
    <!-- endbuild -->

    <!--For production we only include app.min.js genereted by Gulp -->
    <!-- build:js-app -->
    <script src="{% static "scripts/app-dev.js" %}"></script>
    <!-- endbuild -->

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-XXXXX-X', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>